version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/ubuntu-dev:20.04
    steps:
      - checkout:
      - run: echo "Hello, world!"
      - add_ssh_keys:
          fingerprints:
            - "da:8a:9f:ed:28:f4:ca:c2:e0:cb:65:d2:30:2e:f2:16"
      - run: sh ./deploy.sh
